USE [master]
GO

/****** Object:  Database [PaisesInfo]    Script Date: 15/02/2021 00:36:46 ******/
CREATE DATABASE [PaisesInfo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PaisesInfo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PaisesInfo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PaisesInfo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PaisesInfo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PaisesInfo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PaisesInfo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PaisesInfo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PaisesInfo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PaisesInfo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PaisesInfo] SET ARITHABORT OFF 
GO

ALTER DATABASE [PaisesInfo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PaisesInfo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PaisesInfo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PaisesInfo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PaisesInfo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PaisesInfo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PaisesInfo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PaisesInfo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PaisesInfo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PaisesInfo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PaisesInfo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PaisesInfo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PaisesInfo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PaisesInfo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PaisesInfo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PaisesInfo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PaisesInfo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PaisesInfo] SET RECOVERY FULL 
GO

ALTER DATABASE [PaisesInfo] SET  MULTI_USER 
GO

ALTER DATABASE [PaisesInfo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PaisesInfo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PaisesInfo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PaisesInfo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PaisesInfo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PaisesInfo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PaisesInfo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PaisesInfo] SET  READ_WRITE 
GO


